### ISSUE TITLE
Allow new V2 verification attributes to be passed to the gem and use new path [1.6]

### ISSUE THREAD

**Issue by caasssandre** [AddressFinder/addressfinder-ruby#21]
### Description
We want to be able to use the new V2 verification api when doing bulk verification.

This means that the ruby gem should accept the parameters that the new api expects.

These are `gnaf`, `gps`, `ext` and `verification_version` (`paf` was already added earlier in this work, `dpid` will be added in the future if we decide to go down that path)

### Implementation

1. Create a `AddressFinder::V2::Verification` module that will call the v2 API
2. Accept a new attribute `verification_version` in the configuration
3. Call the old module or v2 module based on the `verification_version` included

### Testing
The new attributes sent via the bulk verification are accepted and the expected response is returned.

### Approval

@1mattramsay 
@nigelramsay

**Comment by caasssandre** [comment]
work started in `feature/accept_v2_verification_params`

**Comment by 1mattramsay** [comment]
I agree that we need to ensure customers can gain the V1 experience when using the bulk verification feature from the new V2 API so keeping the response from V@ when GNAF=1&GPS=1&Census=2016 the same as the response from the V1 API is important. 

I think the other options (PAF=1 and PAF=1&GNAF=1) should return the results in a more logical order.

**Comment by caasssandre** [comment]
Testing:

All parameters are accepted, `paf`, `gnaf`, `census`, `post_box` and `ext`

`paf` `gnaf` `post_box` and `census` behave as expected. 'ext' has no effect at this stage, as expected.

Ready to publish
