### ISSUE TITLE
Rename ext to extended

### ISSUE THREAD

**Issue by caasssandre** [AddressFinder/addressfinder-ruby#24]
### Description

We have decided that the new parameter for extended metadata should be renamed `extended` rather than `ext`. See addressfinder/addressfinder-api#989  for details.

### Implementation

Rename every occurrence of `ext` to `extended` this will depend on AddressFinder API handling queries including `extended=1`

### Approval
@erikfercak

**Comment by 1mattramsay** [comment]
Testing: Success

Renaming Ext to Extended works well.

Data is returned when expected and not when not expected.
Ext=1 no longer returns anything.

Ready for prod.
